name: Publish Workflow
on:
  push:
    branches:
      - main

jobs:
  publish:
    if: "!contains(github.event.commits[0].message, '[skip-ci]')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Find Cache Directory
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache Yarn Directory
        uses: actions/cache@v2
        id: cache-yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-nodemodules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-nodemodules-
      - run: yarn
        if: |
          steps.cache-yarn-cache.outputs.cache-hit != 'true' ||
          steps.cache-node-modules.outputs.cache-hit != 'true'

      - name: Run Lint Source
        id: lint
        run: yarn l

      - name: Run Lint Type
        id: linttype
        if: steps.lint.exit_code == 0
        run: yarn l:type

      - name: Run Tests
        id: tests
        if: steps.linttype.exit_code == 0
        run: yarn t:cov

      - name: Create Local Build
        id: build
        if: steps.tests.exit_code == 0
        run: yarn b

      - name: Publish to NPM
        id: publish
        uses: JS-DevTools/npm-publish@v1
        if: steps.tests.build == 0
        with:
          token: ${{ secrets.TOKEN }}

      - name: Update Code Coverage
        uses: codecov/codecov-action@v1
        if: steps.publish.exit_code == 0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
